import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { AiAnalysisResult } from "./AiAnalysisResult";

describe("AiAnalysisResult", () => {
  it("renders completed analysis details and evidence", () => {
    const onApplyRecommendedFilters = vi.fn();
    render(
      <AiAnalysisResult
        onApplyRecommendedFilters={onApplyRecommendedFilters}
        analysis={{
          status: "COMPLETED",
          requestedByOperatorDisplayName: "Sarah Connor",
          requestedAt: "2026-09-05T08:00:00Z",
          result: {
            riskLevel: "MEDIUM",
            summary: "Several suspicious payments were reviewed.",
            recommendations: "Contact the customer care escalation desk.",
            evidence: [
              {
                evidenceId: "evidence-1",
                sourceReference: "policy://policies/risk-signal-handling-v1.md#triggered-rule-response",
                excerpt: "Escalate medium risk findings."
              }
            ]
          }
        }}
      />
    );

    expect(screen.getByText("Risk: MEDIUM")).toHaveClass("risk-medium");
    expect(screen.getByText("Status: COMPLETED")).toHaveClass("status-completed");
    expect(screen.getByText("5 Sept 2026")).toBeInTheDocument();
    expect(screen.getByText("10:00")).toBeInTheDocument();
    expect(screen.getByText("Generated by Sarah Connor")).toBeInTheDocument();
    expect(screen.getByText("Several suspicious payments were reviewed.")).toBeInTheDocument();
    expect(screen.getByText("policy://policies/risk-signal-handling-v1.md#triggered-rule-response"))
      .toBeInTheDocument();
    expect(screen.queryByText("Alt+R")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /Review flagged activity/ }));

    expect(onApplyRecommendedFilters).toHaveBeenCalledOnce();
  });

  it("does not repeat recommendations already included in a structured risk alert summary", () => {
    render(
      <AiAnalysisResult
        analysis={{
          status: "COMPLETED",
          requestedByOperatorDisplayName: "Sarah Connor",
          requestedAt: "2026-09-05T08:00:00Z",
          result: {
            riskLevel: "HIGH",
            summary: `RISK ALERT SUMMARY
Customer ID: customer-1

3. RECOMMENDED OPERATOR ACTION:
   - Escalate to a senior operator.`,
            recommendations: "Escalate to a senior operator.",
            evidence: []
          }
        }}
      />
    );

    expect(screen.getAllByText(/Escalate to a senior operator/)).toHaveLength(1);
  });

  it("renders failed analysis without result details", () => {
    render(
      <AiAnalysisResult
        analysis={{
          status: "FAILED",
          requestedByOperatorDisplayName: "John McClane",
          requestedAt: "2026-09-05T09:00:00Z",
          failureReason: "Vector store unavailable",
          result: null
        }}
      />
    );

    expect(screen.getByText("Status: FAILED")).toHaveClass("status-failed");
    expect(screen.getByText("5 Sept 2026")).toBeInTheDocument();
    expect(screen.getByText("11:00")).toBeInTheDocument();
    expect(screen.getByText("Generated by John McClane")).toBeInTheDocument();
    expect(screen.getByText("Vector store unavailable")).toBeInTheDocument();
  });
});
